local module = require(script.Parent.Parent.Parent.Parent.Parent["alicesaidhi+conch_language"]["0.3.1"]["conch_language"]["src"])
export type LanguageVm  = module.LanguageVm 
export type TypeAnalysisInfo  = module.TypeAnalysisInfo 
export type SimpleValue  = module.SimpleValue 
export type Overload  = module.Overload 
export type Suggestion  = module.Suggestion 
export type Metadata  = module.Metadata 
export type AnalysisArgument  = module.AnalysisArgument 
export type AnalysisResult  = module.AnalysisResult 
export type AnalysisInputState  = module.AnalysisInputState 
export type RunResult  = module.RunResult 
export type LanguageInterface  = module.LanguageInterface 
return module